-- thatswhoi.am schema
-- Run this in the Supabase SQL editor

create table public.profiles (
  id uuid references auth.users(id) primary key,
  slug text unique not null,
  full_name text,
  email text,
  location text,
  avatar_url text,
  is_open_to_work boolean default false,
  archetype text,                      -- 'adapter' | 'climber' | 'builder'
  headline text,                       -- generated by Claude API
  tier text default 'free',           -- 'free' | 'pro'
  last_updated_at timestamptz,
  created_at timestamptz default now()
);

create table public.experiences (
  id uuid default gen_random_uuid() primary key,
  profile_id uuid references public.profiles(id) on delete cascade,
  role text not null,
  company text not null,
  sector text not null,
  years numeric not null,
  description text,
  position integer default 0,
  created_at timestamptz default now()
);

-- Row Level Security
alter table public.profiles enable row level security;
alter table public.experiences enable row level security;

create policy "profili pubblici leggibili da tutti"
  on public.profiles for select using (true);

create policy "solo il proprietario può modificare il proprio profilo"
  on public.profiles for update using (auth.uid() = id);

create policy "inserimento profilo solo per se stessi"
  on public.profiles for insert with check (auth.uid() = id);

create policy "esperienze pubbliche leggibili da tutti"
  on public.experiences for select using (true);

create policy "solo il proprietario può gestire le proprie esperienze"
  on public.experiences for all using (
    auth.uid() = (select p.id from public.profiles p where p.id = profile_id)
  );
